--- 
title: "GDB_DataReview ArcMap Toolbox Tutorials"
author: "Air Force Civil Engineering Center (AFCEC) Geospatial Integration Office (GIO)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [packages.bib]
biblio-style: apalike
link-citations: yes
graphics: yes
classoption: openany
description: "How to use the ArcMap GDB_DataReview Toolbox."
---
\mainmatter

```{r include=FALSE}
library(bookdown)
library(rmarkdown)
library(knitr)
knit_hooks$set(crop = hook_pdfcrop)
options(tinytex.verbose = TRUE)
options(knitr.graphics.auto_pdf = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
# automatically create a bib database for R packages
knitr::write_bib((.packages()), 'packages.bib')
library(knitr)
#opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
opts_chunk$set(fig.retina=2,dpi=96)
```

# Overview {#overview}

This document gives an overview of how to use the GDB_DataReview ArcMap Toolbox.

The GDB_DataReview ArcMap Toolbox provides numerous Python script tools to expedite the review of geodatabases in comparison with a template geodatabase model. This toolbox was developed to aid Air Force (AF) installations in maintaining geospatial data in compliance with the the current Air Force Data Model (GeoBase 3.1.0.1) developed under the [AF GeoBase mission](https://www.sdsfieonline.org/Components/USAF). This data model is based upon the [Spatial Data Standards for Facilities, Infrastructure, and Environment (SDSFIE)](https://www.sdsfieonline.org/) SDSFIE-V 3.1 Gold model, which complies with  the Department of Defense Instruction (DoDI) 8130.01, *Installation Geospatial Information and Service* (IGI&S), while also providing some flexibility within the program to aid the AF mission. As part of the IGI&S program, this toolbox also aids in standardizing methods to adhere to the Fiscal Year 2017 CIP data call required by DoDI 8130.01.

The GDB_DataReview Toolbox provides methods to:

* Update feature class data using both [tabular](#joinCalc) and [spatial](#spatjoinCalc) joins,
* Find [duplicate geometries](#dupGeom), delete [duplicate features](#dupFeats), and [check/repair](#chkGeom) feature geometries,
* Standardize [road prefixes, names and suffixes](#std3) or [building addresses](#stdAdd1),
* [Search for](#indtSearch) and [summarize](#summIndt) indeterminant and missing data in a geodatabase when compared with a template geodatabase
* Batch [exporting](#exMeta) and [importing](#imMeta) geodatabase metadata



